### ISSUE TITLE
Using a mixed in var between let

### ISSUE THREAD

**Issue by kylebot0** [robert-hoekstra/web-app-from-scratch-1920#1]
https://github.com/robert-hoekstra/web-app-from-scratch-1920/blob/b757122d7baf2a5e70c02e465118e525856d0c53/docs/js/app.js#L38

On this line i can see that you used a var, in an application that uses mostly es6.

**Comment by robert-hoekstra** [comment]
Fixed! Thanks for finding this ugly written piece of junk!
