### ISSUE TITLE
Interaction diagram nog vrij ingewikkeld

### ISSUE THREAD

**Issue by ManoukK** [robert-hoekstra/web-app-from-scratch-1920#14]
Je interaction diagram is nog best ingewikkeld vind ik. Dat komt omdat er veel lijnen lopen en dingen ook tegelijkertijd starten. Ik begrijp wat er gebeurd maar misschien kan je deze diagram wat meer "rust" geven door de elementen wat verder uit elkaar te zetten en de elementen die met elkaar te maken hebben wat dichterbij elkaar te plaatsten. 

Dit hoeft niet hoor want na een tijdje kijken zie ik de logica wel

**Comment by robert-hoekstra** [comment]
Ik ga kijken of ik nog nieuwe diagrammen kan maken. Keep you posted!
