### ISSUE TITLE
Labels aanpassen in je website

### ISSUE THREAD

**Issue by ManoukK** [robert-hoekstra/web-app-from-scratch-1920#15]
Je hebt nu je site zo gestructureerd:
NAME: Kamino
ROTATION_PERIOD: 27
ORBITAL_PERIOD: 463
DIAMETER: 19720 

Maar misschien is het wel leuk om de data in een soort zin te verwerken. 
bijvoorbeeld 1 week duurt 27 dagen, 1 jaar duurt 463 dagen.

**Comment by robert-hoekstra** [comment]
Ben hier helaas niet aan toegekomen maar zeker een goede feature voor in de toekomst!
