### ISSUE TITLE
You're using the same pictures

### ISSUE THREAD

**Issue by kylebot0** [robert-hoekstra/web-app-from-scratch-1920#2]
https://github.com/robert-hoekstra/web-app-from-scratch-1920/blob/b757122d7baf2a5e70c02e465118e525856d0c53/docs/js/app.js#L69

Pictures should be randomised, but it keeps giving the same pictures. You should be giving an id with the url.

**Comment by robert-hoekstra** [comment]
Thanks! I was wondering how I could get this effect. I am going to change the image API with one that searches something related to the item in the section.
