### ISSUE TITLE
Beetje omslachtige while

### ISSUE THREAD

**Issue by Mokerstier** [robert-hoekstra/web-app-from-scratch-1920#20]
https://github.com/robert-hoekstra/web-app-from-scratch-1920/blob/83a4e7c115099bb72d395fdce3edb86969de5677/docs/js/app.js#L26-L31

je kan gewoon zeggen yourArray = [] dan heb je geen while nodig ;)

**Comment by robert-hoekstra** [comment]
Ik vond dit een nettere (en snellere) methode dan innerhtml. vandaar deze toepassing.
