### ISSUE TITLE
Rubric

### ISSUE THREAD

**Issue by Mokerstier** [robert-hoekstra/web-app-from-scratch-1920#21]
Consistency:
Je gebruikt soms ";" aan het einde van je block en soms niet dit kan je nog wel ff netter maken

SCOPING: gaat denk ik wel goed; Next step: MODULES maar hier werk je al naar toe!

DATA: Map filter reduce, ik denk dat dit wel goed komt je hebt het alleen nog niet.
           Je rendert ook al je data naar je HTML dus "templating" gaat ook goed

STATES & ROUTES: ik denk zodra je routing gefixt is dit ook allemaal in orde is

Overal: nog wel ff wat werk te doen maar je bent zeker op weg naar een dikke voldoende IMO

Groetjes MokerStier

**Comment by robert-hoekstra** [comment]
Thanks mokerstier! ben er mee aan de slag gegaan :)
