### ISSUE TITLE
querySelector should be getElementById

### ISSUE THREAD

**Issue by kylebot0** [robert-hoekstra/web-app-from-scratch-1920#4]
https://github.com/robert-hoekstra/web-app-from-scratch-1920/blob/b757122d7baf2a5e70c02e465118e525856d0c53/docs/js/app.js#L1-L3

On the last two lines you're using getElementById to get the element, and to get the first element you're using a querySelector to get an Id. So the first line should be an document.getElementById.

**Comment by robert-hoekstra** [comment]
Sharp!
