### ISSUE TITLE
Goed gedaan robert

### ISSUE THREAD

**Issue by Ramon96** [robert-hoekstra/web-app-from-scratch-1920#6]
Netjes man, weinig op te merken.

Je bent al ver.
Je schrijft je code netjes en je functie's zijn duidelijk. 
Punten waar je nog aan kan werken

- Afbeeldingen kloppen nog niet helemaal
- Readme kan je nog verder afmaken. 
- Er staan nog wat variabelen in de global scrope

Ga zo door en het moet zeker goedkomen

**Comment by robert-hoekstra** [comment]
Thanks Ramon!
